### PR TITLE
Repository cleanup

### PR DESCRIPTION
**Pull request by porst17**
In order to release the next version of the heartbeat stuff, I started to clean up the repository. Remove outdated things, assigned proper names, separate what's supposed to be separate (e.g. Python client and server).

@malex984 could you please further clean up the heartbeat server (Python) and clients (Bash, Python):
- [x] remove comments with outdated code
- [x] check your TODOs and
   - [x] ~~put them into the issue tracker~~
   - [x] remove them if they are invalid/outdated
- [x] the BASH version contains references to `appchoo` and `txt2jpg.sh`. Can this be replaced?
- [x] add a `README.md` to each subfolder that illustrates the usage of the scripts/library, explains build steps, list dependencies if necessary:
   - [x] Python server
   - [x] Clients and client libraries:
     - [x] JavaScript 
     - [x] Python 
     - [x] Bash
- [x] document the API if any of your scripts can act as a library (preferably, use inline documentation in your code, then generate an `API.md` file)
   - [x] Python server (part of `README.md`)
   - [x] Clients and client libraries:
     - [x] JavaScript 
     - [x] Python (part of `README.md`) 
     - [x] Bash
- [x] ~~if the Python code imports any non-standard library, add a `requirements.txt` file~~

Additionally (identified by @malex984),
- [x] collect/update HB-related client wrappers (`hb.sh`, `hb_dummy.sh`, `hb_wrapper.sh`) to this repository from other repos
- [x] create shared bash library to be sources by those wrappers
- [x] remove dummy in favor of wrapper with 3 options for sending init/done/ping signals
- [x] add documentation
- [x] remove original HB design from the main readme + clean-up / separate internal docs from it
- [x] refactor HB server: e.g. remove threading.Timer in favor of synchronous checking/cleanup of late visit-entries (just iterate visits) before processing new requests (via `do_GET`). Note that HB server is *synchronous*!

Finally, we need to clean up the main `README.md`:
- [x] it should only contain the protocol definition and then
- [x] link to the reference implementations of the server and the clients.

and

- [x] update `CHANGELOG.md`

Once this is done, we can draft the final `v1.0.0` release.

### CODE REVIEW

**Comment by malex984** [comment]
Additionally  

[ ] collect/update HB-related client wrappers (`hb.sh`, `hb_dummy.sh`, `hb_wrapper.sh`) to this repository from other repos
[ ] create shared bash library to be sources by those wrappers
[ ] remove dummy in favor of wrapper with 3 options for sending init/done/ping signals
[ ] add documentation
[ ] remove original HB design from the main readme + clean-up / separate internal docs from it
[ ] refactor HB server: e.g. remove threading.Timer in favor of synchronous checking/cleanup of late visit-entries (just iterate visits) before processing new requests (via `do_GET`). Note that HB server is *synchronous*!

**Review by porst17 — COMMENTED** [review]
This commit is mixing different things again:
- seconds -> milliseconds
- removing comments
- fixing exit codes
- importing new scripts
- various small changes
Please refactor this into individual, but meaningful commits.

**Comment by malex984** [comment]
Should i remove my commit from this PR and create a separate PR for those changes?

**Comment by porst17** [comment]
Remove it and split. I didn't pull and even if I had, I would just reset my local branch.

**Comment by porst17** [comment]
BTW: Your commit authors are broken again. If you are using multiple identities on your machine, please configure them on a per-repo basis (locally) to avoid this in the future.

**Review by porst17 — COMMENTED** [review]
I looks like the python heartbeat client and servers are sending around floating point numbers instead of integers. Is this correct (I just looked at the code, not tested it)? I know, its not set in stone in the protocol, but I would like to restrict it to integer values. Otherwise you have problems with different formatting of floating point numbers again. I doesn't matter much to me what you use internally. But the interval in the protocol should be represented by integer numbers.

**Comment by porst17** [comment]
Comment on the symlink-based solution for the BASH scripts (no action required): NTFS also supports symlinks and they can be [used from within cygwin and mingw](https://stackoverflow.com/a/18659632/1496589). But they can only be created with admin privileges. Just using them should be possible with regular user-level privileges. So I suppose your symlink-based solution can be considered kind of platform independent. It should also work with NTFS on Windows without cygwin and mingw if you have a static BASH binary. But of course, BASH is of kind of useless without the other command line utilities that are part of mingw and cygwin.

**Comment by malex984** [comment]
@porst17 no more floating-point numbers are floating around - only integers!

**Comment by porst17** [comment]
I updated the main and the servers `README.md` and would consider them ready for release.

@malex984 I updated the list of TODOs. Basically, some `README.md` and API documentation is still missing from your side. If API documentation doesn't make sense in certain sub-folders, just skip it, strike-through the TODO above and mark it as done.

**Comment by porst17** [comment]
@malex984 I updated the changelog, but some changes related to the Python and Bash implementation might be missing. Please check and add the missing pieces if necessary.

**Comment by malex984** [comment]
@porst17 where do we draw the line? What will not be released?

**Comment by porst17** [comment]
Seems the BASH `README.md` is still missing! But we are almost done! :+1:

**Review by malex984 — APPROVED** [review]

**Pull request merged**
