### PR TITLE
Feature/send method

### PR DESCRIPTION
**Pull request by porst17**
Add generic `send` methods and fix a couple of inconsistencies around previous `send` methds.

@malex984 You can already test it, but a couple of smaller things are missing. So don't merge it.

### CODE REVIEW

**Review by porst17 — COMMENTED** [review]
Missing:
- [x] support for `setInterval(-1)` for disabling automatic heartbeat pings
- [x] keep previous `XMLHttpRequest` objects in a queue because all unfinished requests have to be aborted before `hb_done` command to conform with the protocol
- [ ] ~add compiled JSdoc file (include library/API version!!)~
- [x] add timeout for requests

**Comment by porst17** [comment]
I found a couple of bugs. Please stop testing if you are already on it. I'll push the fixes ASAP.

**Comment by porst17** [comment]
I think it's done now. Please review it again.

**Comment by malex984** [comment]
@porst17 new JS library seems to work for my tests. Unfortunately i have too little experience with JS to really review/evaluate it! It is not clear to be how to use the new `prototype` thing - would be nice to see more/updated usage examples for newly introduces/exposed functionality!

**Comment by porst17** [comment]
`prototype` is just the pre ECMAScript 2015 way of implementing non-static methods of classes:
```JavaScript
function MyClass() { this.a=1; };
MyClass.prototype.getA = function() { return this.a; }
var o = new MyClass();
o.getA(); // => 1
```
It's just a regular method that has access to the `this` pointer of the main object.

Regarding the documentation: I would rather add an example to the `README.md` later on.

Can I merge it?

**Review by malex984 — APPROVED** [review]
works in my tests

**Comment by malex984** [comment]
@porst17 yes, please merge it

**Pull request merged**
